Added delete booking
frokostklubben/evening-school pull request #36
Opened 2024-06-09 12:15 UTC by norskemarcus

+ Rest of edit booking fixed update automatically update of list

2024-06-10 10:42 UTC, tomm8231 commented on client/src/components/DatePicker.svelte
> +	//export let value;
sletski

2024-06-10 10:42 UTC, tomm8231 commented on client/src/components/DatePicker.svelte
> +		//	value = event.detail;
sletski

2024-06-10 10:46 UTC, tomm8231 commented on client/src/components/DatePickerBasic.svelte
> +<script>
slet fil

2024-06-10 11:08 UTC, tommyhellejensen commented on client/src/routes/edit-booking/+page.svelte
lav check på om ændrede tider på bookings er ledige

2024-06-10 11:09 UTC, tomm8231 requested changes
Godt arbejde. Se mine kommentarer

2024-06-12 07:00 UTC, tomm8231 commented on client/src/components/ModalEditBooking.svelte
> +				body: JSON.stringify({ bookingDates: booking, ignoreSetupTime })
virker ignoreSetupTime?

2024-06-12 07:03 UTC, tomm8231 commented on client/src/components/ModalEditBooking.svelte
> +						checkBookingDate();
checkAndSaveBooking

2024-06-12 07:04 UTC, tomm8231 commented on client/src/routes/room-search/+page.svelte
> +
Slet

2024-06-12 07:05 UTC, tomm8231 commented on client/src/routes/room-search/+page.svelte
> +			// endTime: formatTime(endTime)
Slet

2024-06-12 07:22 UTC, tomm8231 commented on client/src/routes/+layout.svelte
> +								bind:value={testUser.email}
ændr testUser til noget andet. F.eks. userToLogin

2024-06-12 07:35 UTC, tomm8231 commented on client/src/routes/room-search/+page.svelte
> +
slet

2024-06-12 07:39 UTC, norskemarcus commented on client/src/components/ModalEditBooking.svelte
> +				body: JSON.stringify({ bookingDates: booking, ignoreSetupTime })
Nej, hellere ikke i bookingsiden!

2024-06-12 07:40 UTC, tomm8231 commented on server/routers/bookingsRouter.js
> +    console.log(formattedBooking)
slet

2024-06-12 07:41 UTC, tomm8231 commented on server/routers/classroomsRouter.js
> +// TODO OBS OBS BUG: Skal en kontoransat skulle kunne redigere et lokale? admincheck addes evt
slet

2024-06-12 07:45 UTC, tomm8231 requested changes
Godt arbejde, se mine kommentarer

2024-06-12 07:56 UTC, tomm8231 commented on server/middlewares/validateUser.js
> +// TODO: BRUGES DETTE IKKE LÆNGERE???
slet fil

2024-06-12 07:59 UTC, tomm8231 requested changes
Slet validateUser.js

2024-06-12 08:27 UTC, tomm8231 approved these changes

2024-06-12 08:27 UTC, merged